### ISSUE TITLE
Any considerations for VS 2022

### ISSUE THREAD

**Issue by caryyu** [etorth/mir2x#46]
From the tutorials, seems like it only supports Linux-based OS if we want it to be compiled smoothly, I'd like to know if there're any plans to support the native Windows in the future instead of the WSL/WSL2 workaround.

In addition, what's the completion of the game like? does it fulfill 90% progress of the original v1.45?

**Comment by etorth** [comment]
It's used to be able to compile with VS.
Later because of the VS coroutine support is not good, the compilation is broken, and I didn't maintain it anymore.

The project is still far from complete, I will stay with WSL till it's close to "done".
In my imagination, it should micmic v1.45, plus some instant messager support.

**Comment by caryyu** [comment]
@etorth Thanks for the reply, I realized the whole approach is completely new after I read some code in comparing to what the mainstream looks like in Delphi-based ones. quite curious about abandoning the legacy server configurations - those txt files.
