### ISSUE TITLE
need some help on sdl2 ime support

### ISSUE THREAD

**Issue by shellohunter** [etorth/mir2x#48]
I'm coding a small text input widget using sdl2. What I'm trying to do is to support system IME (CJK) with IME candidates shown. Unfortunately I have not make it yet. After googling around I found your post on sdl2 forum. I'm wondering if I can get some help here.

I checked the code here. It seems mir2x does not support system IME, but implemented a in-game input board based on libpinyin. Am I correct? Is there any issue that made you drop the sdl2 input API (such as SDL_StartTextInput)?

ref: https://github.com/libsdl-org/SDL/issues/2243#issuecomment-1160887246

**Comment by etorth** [comment]
because I never made it work...
if you somehow made it, please let me know.

**Comment by shellohunter** [comment]
:)
well, let's hope there would be a solution somehow.

**Comment by shellohunter** [comment]
here's the good news: I made it work.
the aha moment came to me as I occasionally found this commit: https://github.com/ocornut/imgui/commit/fab96a6e59302fcaba2a17ea8d5a257a4fcf0d4f
verified ok on win10 and mac, no linux desktop to try though.

**Comment by MirageCode** [comment]
@etorth I have had this working in Linux before. I just followed the [tutorial](https://wiki.libsdl.org/SDL2/Tutorials-TextInput).

What you'd need to change:

1. When the textbox receives focus, call `SDL_SetTextInputRect(&rect)` and `SDL_StartTextInput()`, where `rect` is an `SDL_Rect` containing the position and dimensions of the textbox; and, when it loses focus, call `SDL_StopTextInput()`.
2. Stop using `SDL_KEYDOWN` to handle text input. Use it to handle `SDLK_RETURN`, `SDLK_BACKSPACE` etc. as you are, but remove the `default` part in `inputline.cpp`. Instead, use `SDL_TEXTINPUT` events to handle text input. These contain a string of text which you need to copy to your textbox. If the system IME is open, this text will be the committed text it returns; otherwise, it will contain just a single character directly from the keyboard.
3. Add member variables for the composition text and composition cursor (separate to your main textbox cursor).
4. Handle `SDL_TEXTEDITING` events; copy the text and cursor from these events to your new member variables.
5. When rendering, if the composition text is empty, render everything as it is currently. If it isn't empty, instead of drawing your main cursor, render the composition text at the position of the main cursor, and draw the cursor at the position of the composition cursor, relative to the position of the composition text. You might want to draw the composition text in a different colour, or draw a line underneath it, to indicate that this text isn't committed to the textbox.
